//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ApplicationInspector.Commands.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.ApplicationInspector.Commands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ANALYZE_COMPRESSED_ERROR {
            get {
                return ResourceManager.GetString("ANALYZE_COMPRESSED_ERROR", resourceCulture);
            }
        }
        
        internal static string ANALYZE_COMPRESSED_FILESIZE_WARN {
            get {
                return ResourceManager.GetString("ANALYZE_COMPRESSED_FILESIZE_WARN", resourceCulture);
            }
        }
        
        internal static string ANALYZE_COMPRESSED_FILETYPE {
            get {
                return ResourceManager.GetString("ANALYZE_COMPRESSED_FILETYPE", resourceCulture);
            }
        }
        
        internal static string ANALYZE_COMPRESSED_PROCESSING {
            get {
                return ResourceManager.GetString("ANALYZE_COMPRESSED_PROCESSING", resourceCulture);
            }
        }
        
        internal static string ANALYZE_EXCLUDED_TYPE_SKIPPED {
            get {
                return ResourceManager.GetString("ANALYZE_EXCLUDED_TYPE_SKIPPED", resourceCulture);
            }
        }
        
        internal static string ANALYZE_FILESIZE_SKIPPED {
            get {
                return ResourceManager.GetString("ANALYZE_FILESIZE_SKIPPED", resourceCulture);
            }
        }
        
        internal static string ANALYZE_FILES_PROCESSED_PCNT {
            get {
                return ResourceManager.GetString("ANALYZE_FILES_PROCESSED_PCNT", resourceCulture);
            }
        }
        
        internal static string ANALYZE_FILE_TYPE_OPEN {
            get {
                return ResourceManager.GetString("ANALYZE_FILE_TYPE_OPEN", resourceCulture);
            }
        }
        
        internal static string ANALYZE_LANGUAGE_NOTFOUND {
            get {
                return ResourceManager.GetString("ANALYZE_LANGUAGE_NOTFOUND", resourceCulture);
            }
        }
        
        internal static string ANALYZE_NOPATTERNS {
            get {
                return ResourceManager.GetString("ANALYZE_NOPATTERNS", resourceCulture);
            }
        }
        
        internal static string ANALYZE_NOSUPPORTED_FILETYPES {
            get {
                return ResourceManager.GetString("ANALYZE_NOSUPPORTED_FILETYPES", resourceCulture);
            }
        }
        
        internal static string ANALYZE_OUTPUT_FILE {
            get {
                return ResourceManager.GetString("ANALYZE_OUTPUT_FILE", resourceCulture);
            }
        }
        
        internal static string ANALYZE_REPORTSIZE_WARN {
            get {
                return ResourceManager.GetString("ANALYZE_REPORTSIZE_WARN", resourceCulture);
            }
        }
        
        internal static string ANALYZE_UNCOMPRESSED_FILETYPE {
            get {
                return ResourceManager.GetString("ANALYZE_UNCOMPRESSED_FILETYPE", resourceCulture);
            }
        }
        
        internal static string ANALYZE_UNSUPPORTED_COMPR_TYPE {
            get {
                return ResourceManager.GetString("ANALYZE_UNSUPPORTED_COMPR_TYPE", resourceCulture);
            }
        }
        
        internal static string BROWSER_ENVIRONMENT_VAR {
            get {
                return ResourceManager.GetString("BROWSER_ENVIRONMENT_VAR", resourceCulture);
            }
        }
        
        internal static string BROWSER_START_FAIL {
            get {
                return ResourceManager.GetString("BROWSER_START_FAIL", resourceCulture);
            }
        }
        
        internal static string BROWSER_START_SUCCESS {
            get {
                return ResourceManager.GetString("BROWSER_START_SUCCESS", resourceCulture);
            }
        }
        
        internal static string CMD_COMPLETED {
            get {
                return ResourceManager.GetString("CMD_COMPLETED", resourceCulture);
            }
        }
        
        internal static string CMD_CRITICAL_FILE_ERR {
            get {
                return ResourceManager.GetString("CMD_CRITICAL_FILE_ERR", resourceCulture);
            }
        }
        
        internal static string CMD_INVALID_ARG_VALUE {
            get {
                return ResourceManager.GetString("CMD_INVALID_ARG_VALUE", resourceCulture);
            }
        }
        
        internal static string CMD_INVALID_FILE_OR_DIR {
            get {
                return ResourceManager.GetString("CMD_INVALID_FILE_OR_DIR", resourceCulture);
            }
        }
        
        internal static string CMD_INVALID_RULE_PATH {
            get {
                return ResourceManager.GetString("CMD_INVALID_RULE_PATH", resourceCulture);
            }
        }
        
        internal static string CMD_NORULES_SPECIFIED {
            get {
                return ResourceManager.GetString("CMD_NORULES_SPECIFIED", resourceCulture);
            }
        }
        
        internal static string CMD_PREPARING_REPORT {
            get {
                return ResourceManager.GetString("CMD_PREPARING_REPORT", resourceCulture);
            }
        }
        
        internal static string CMD_REPORT_DONE {
            get {
                return ResourceManager.GetString("CMD_REPORT_DONE", resourceCulture);
            }
        }
        
        internal static string CMD_REQUIRED_ARG_MISSING {
            get {
                return ResourceManager.GetString("CMD_REQUIRED_ARG_MISSING", resourceCulture);
            }
        }
        
        internal static string CMD_RUNNING {
            get {
                return ResourceManager.GetString("CMD_RUNNING", resourceCulture);
            }
        }
        
        internal static byte[] comments {
            get {
                object obj = ResourceManager.GetObject("comments", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] languages {
            get {
                object obj = ResourceManager.GetObject("languages", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static string PACK_MISSING_OUTPUT_ARG {
            get {
                return ResourceManager.GetString("PACK_MISSING_OUTPUT_ARG", resourceCulture);
            }
        }
        
        internal static string RUNTIME_ERROR_NAMED {
            get {
                return ResourceManager.GetString("RUNTIME_ERROR_NAMED", resourceCulture);
            }
        }
        
        internal static string RUNTIME_ERROR_PRELOG {
            get {
                return ResourceManager.GetString("RUNTIME_ERROR_PRELOG", resourceCulture);
            }
        }
        
        internal static string RUNTIME_ERROR_UNNAMED {
            get {
                return ResourceManager.GetString("RUNTIME_ERROR_UNNAMED", resourceCulture);
            }
        }
        
        internal static string TAGDIFF_NO_TAGS_FOUND {
            get {
                return ResourceManager.GetString("TAGDIFF_NO_TAGS_FOUND", resourceCulture);
            }
        }
        
        internal static string TAGDIFF_RESULTS_DIFFER {
            get {
                return ResourceManager.GetString("TAGDIFF_RESULTS_DIFFER", resourceCulture);
            }
        }
        
        internal static string TAGDIFF_RESULTS_FAIL {
            get {
                return ResourceManager.GetString("TAGDIFF_RESULTS_FAIL", resourceCulture);
            }
        }
        
        internal static string TAGDIFF_RESULTS_GAP {
            get {
                return ResourceManager.GetString("TAGDIFF_RESULTS_GAP", resourceCulture);
            }
        }
        
        internal static string TAGDIFF_RESULTS_SUCCESS {
            get {
                return ResourceManager.GetString("TAGDIFF_RESULTS_SUCCESS", resourceCulture);
            }
        }
        
        internal static string TAGDIFF_RESULTS_TEST_TYPE {
            get {
                return ResourceManager.GetString("TAGDIFF_RESULTS_TEST_TYPE", resourceCulture);
            }
        }
        
        internal static string TAGDIFF_SAME_FILE_ARG {
            get {
                return ResourceManager.GetString("TAGDIFF_SAME_FILE_ARG", resourceCulture);
            }
        }
        
        internal static string TAGTEST_RESULTS_FAIL {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_FAIL", resourceCulture);
            }
        }
        
        internal static string TAGTEST_RESULTS_NONE {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_NONE", resourceCulture);
            }
        }
        
        internal static string TAGTEST_RESULTS_SUCCESS {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_SUCCESS", resourceCulture);
            }
        }
        
        internal static string TAGTEST_RESULTS_TAGS_FOUND {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_TAGS_FOUND", resourceCulture);
            }
        }
        
        internal static string TAGTEST_RESULTS_TAGS_MISSING {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_TAGS_MISSING", resourceCulture);
            }
        }
        
        internal static string TAGTEST_RESULTS_TEST_TYPE {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_TEST_TYPE", resourceCulture);
            }
        }
        
        internal static string VERIFY_RULES_RESULTS_FAIL {
            get {
                return ResourceManager.GetString("VERIFY_RULES_RESULTS_FAIL", resourceCulture);
            }
        }
        
        internal static string VERIFY_RULES_RESULTS_SUCCESS {
            get {
                return ResourceManager.GetString("VERIFY_RULES_RESULTS_SUCCESS", resourceCulture);
            }
        }
        
        internal static string VERIFY_RULE_FAILED {
            get {
                return ResourceManager.GetString("VERIFY_RULE_FAILED", resourceCulture);
            }
        }
    }
}
