//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ApplicationInspector.Commands.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ApplicationInspector.Commands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem while decompressing {0}: Unzip and try running on uncompressed files.
        /// </summary>
        internal static string ANALYZE_COMPRESSED_ERROR {
            get {
                return ResourceManager.GetString("ANALYZE_COMPRESSED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing may take longer for larger files.
        /// </summary>
        internal static string ANALYZE_COMPRESSED_FILESIZE_WARN {
            get {
                return ResourceManager.GetString("ANALYZE_COMPRESSED_FILESIZE_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compressed.
        /// </summary>
        internal static string ANALYZE_COMPRESSED_FILETYPE {
            get {
                return ResourceManager.GetString("ANALYZE_COMPRESSED_FILETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompressing files....
        /// </summary>
        internal static string ANALYZE_COMPRESSED_PROCESSING {
            get {
                return ResourceManager.GetString("ANALYZE_COMPRESSED_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File skipped: Name or path in exclude list. {0}.
        /// </summary>
        internal static string ANALYZE_EXCLUDED_TYPE_SKIPPED {
            get {
                return ResourceManager.GetString("ANALYZE_EXCLUDED_TYPE_SKIPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine file type.  File open error for {0}.
        /// </summary>
        internal static string ANALYZE_FILE_TYPE_OPEN {
            get {
                return ResourceManager.GetString("ANALYZE_FILE_TYPE_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% source files processed.
        /// </summary>
        internal static string ANALYZE_FILES_PROCESSED_PCNT {
            get {
                return ResourceManager.GetString("ANALYZE_FILES_PROCESSED_PCNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File skipped: File size is too large.  {0}.
        /// </summary>
        internal static string ANALYZE_FILESIZE_SKIPPED {
            get {
                return ResourceManager.GetString("ANALYZE_FILESIZE_SKIPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file does not have an html or htm extension and may not open properly in your browser.
        /// </summary>
        internal static string ANALYZE_HTML_EXTENSION {
            get {
                return ResourceManager.GetString("ANALYZE_HTML_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File skipped: Language not found for file {0}.
        /// </summary>
        internal static string ANALYZE_LANGUAGE_NOTFOUND {
            get {
                return ResourceManager.GetString("ANALYZE_LANGUAGE_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow duplicate matches argument not supported for html output format.  Select a different output format (text/json) or remove the argument..
        /// </summary>
        internal static string ANALYZE_NODUPLICATES_HTML_FORMAT {
            get {
                return ResourceManager.GetString("ANALYZE_NODUPLICATES_HTML_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pattern matches were detected for files in source path.
        /// </summary>
        internal static string ANALYZE_NOPATTERNS {
            get {
                return ResourceManager.GetString("ANALYZE_NOPATTERNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file types found in source path that are supported.
        /// </summary>
        internal static string ANALYZE_NOSUPPORTED_FILETYPES {
            get {
                return ResourceManager.GetString("ANALYZE_NOSUPPORTED_FILETYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output.html file size is large and may render slowly.  Consider running using alternate output format options as needed..
        /// </summary>
        internal static string ANALYZE_REPORTSIZE_WARN {
            get {
                return ResourceManager.GetString("ANALYZE_REPORTSIZE_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple tags only argument not supported for html output format.  Select a different output format or remove the argument.
        /// </summary>
        internal static string ANALYZE_SIMPLETAGS_HTML_FORMAT {
            get {
                return ResourceManager.GetString("ANALYZE_SIMPLETAGS_HTML_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uncompressed.
        /// </summary>
        internal static string ANALYZE_UNCOMPRESSED_FILETYPE {
            get {
                return ResourceManager.GetString("ANALYZE_UNCOMPRESSED_FILETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsupported.
        /// </summary>
        internal static string ANALYZE_UNSUPPORTED_COMPR_TYPE {
            get {
                return ResourceManager.GetString("ANALYZE_UNSUPPORTED_COMPR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch output.html automatically.  Set the BROWSER environment variable to your desired browser and try again or launch your browser and navigate to the file to view the report file manually..
        /// </summary>
        internal static string BROWSER_ENVIRONMENT_VAR {
            get {
                return ResourceManager.GetString("BROWSER_ENVIRONMENT_VAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch output.html in default browser.  Launch your browser manually to view output.html report file.
        /// </summary>
        internal static string BROWSER_START_FAIL {
            get {
                return ResourceManager.GetString("BROWSER_START_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening default browser to output.html report.
        /// </summary>
        internal static string BROWSER_START_SUCCESS {
            get {
                return ResourceManager.GetString("BROWSER_START_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} command completed.
        /// </summary>
        internal static string CMD_COMPLETED {
            get {
                return ResourceManager.GetString("CMD_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error processing file {0}.
        /// </summary>
        internal static string CMD_CRITICAL_FILE_ERR {
            get {
                return ResourceManager.GetString("CMD_CRITICAL_FILE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} argument value.
        /// </summary>
        internal static string CMD_INVALID_ARG_VALUE {
            get {
                return ResourceManager.GetString("CMD_INVALID_ARG_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file or directory {0}.
        /// </summary>
        internal static string CMD_INVALID_FILE_OR_DIR {
            get {
                return ResourceManager.GetString("CMD_INVALID_FILE_OR_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested log file {0}) exist but is not recognized as an application log. Provide a different value or delete the file and try again..
        /// </summary>
        internal static string CMD_INVALID_LOG_PATH {
            get {
                return ResourceManager.GetString("CMD_INVALID_LOG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid rule path {0}.
        /// </summary>
        internal static string CMD_INVALID_RULE_PATH {
            get {
                return ResourceManager.GetString("CMD_INVALID_RULE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No output specified.  Raise the console versosity or provide an output file argument..
        /// </summary>
        internal static string CMD_NO_OUTPUT {
            get {
                return ResourceManager.GetString("CMD_NO_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rules specified.  At least one valid rules path required.
        /// </summary>
        internal static string CMD_NORULES_SPECIFIED {
            get {
                return ResourceManager.GetString("CMD_NORULES_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing report.
        /// </summary>
        internal static string CMD_PREPARING_REPORT {
            get {
                return ResourceManager.GetString("CMD_PREPARING_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional details may be found in log file at {0}.
        /// </summary>
        internal static string CMD_REMINDER_CHECK_LOG {
            get {
                return ResourceManager.GetString("CMD_REMINDER_CHECK_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} report completed.
        /// </summary>
        internal static string CMD_REPORT_DONE {
            get {
                return ResourceManager.GetString("CMD_REPORT_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required {0} argument missing.
        /// </summary>
        internal static string CMD_REQUIRED_ARG_MISSING {
            get {
                return ResourceManager.GetString("CMD_REQUIRED_ARG_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} command running.
        /// </summary>
        internal static string CMD_RUNNING {
            get {
                return ResourceManager.GetString("CMD_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See output file at {0}.
        /// </summary>
        internal static string CMD_VIEW_OUTPUT_FILE {
            get {
                return ResourceManager.GetString("CMD_VIEW_OUTPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] comments {
            get {
                object obj = ResourceManager.GetObject("comments", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] languages {
            get {
                object obj = ResourceManager.GetObject("languages", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file not specified for custom rules pack command.
        /// </summary>
        internal static string PACK_MISSING_OUTPUT_ARG {
            get {
                return ResourceManager.GetString("PACK_MISSING_OUTPUT_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack default rules request from outside CLI call not supported.  Use custom rules option..
        /// </summary>
        internal static string PACK_RULES_NO_CLI_DEFAULT {
            get {
                return ResourceManager.GetString("PACK_RULES_NO_CLI_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate local default rules folder.  This command is intended to be run as part of the source code build operation only.  Use the custom rules option instead..
        /// </summary>
        internal static string PACK_RULES_NO_DEFAULT {
            get {
                return ResourceManager.GetString("PACK_RULES_NO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional details may be found in log file at {0}.
        /// </summary>
        internal static string RUNTIME_ERROR_NAMED {
            get {
                return ResourceManager.GetString("RUNTIME_ERROR_NAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional information or log available.
        /// </summary>
        internal static string RUNTIME_ERROR_PRELOG {
            get {
                return ResourceManager.GetString("RUNTIME_ERROR_PRELOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional details may be found in log file at {0}.
        /// </summary>
        internal static string RUNTIME_ERROR_UNNAMED {
            get {
                return ResourceManager.GetString("RUNTIME_ERROR_UNNAMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags found in one or both source paths.
        /// </summary>
        internal static string TAGDIFF_NO_TAGS_FOUND {
            get {
                return ResourceManager.GetString("TAGDIFF_NO_TAGS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files contain tag differences: .
        /// </summary>
        internal static string TAGDIFF_RESULTS_DIFFER {
            get {
                return ResourceManager.GetString("TAGDIFF_RESULTS_DIFFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        internal static string TAGDIFF_RESULTS_FAIL {
            get {
                return ResourceManager.GetString("TAGDIFF_RESULTS_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags in {0} not detected in {1}:.
        /// </summary>
        internal static string TAGDIFF_RESULTS_GAP {
            get {
                return ResourceManager.GetString("TAGDIFF_RESULTS_GAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to succeeded.
        /// </summary>
        internal static string TAGDIFF_RESULTS_SUCCESS {
            get {
                return ResourceManager.GetString("TAGDIFF_RESULTS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test for all [{0}] in source.
        /// </summary>
        internal static string TAGDIFF_RESULTS_TEST_TYPE {
            get {
                return ResourceManager.GetString("TAGDIFF_RESULTS_TEST_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same file passed in for both sources. Test terminated.
        /// </summary>
        internal static string TAGDIFF_SAME_FILE_ARG {
            get {
                return ResourceManager.GetString("TAGDIFF_SAME_FILE_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        internal static string TAGTEST_RESULTS_FAIL {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string TAGTEST_RESULTS_NONE {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to succeeded.
        /// </summary>
        internal static string TAGTEST_RESULTS_SUCCESS {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} in source.
        /// </summary>
        internal static string TAGTEST_RESULTS_TAGS_FOUND {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_TAGS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing {0} in source.
        /// </summary>
        internal static string TAGTEST_RESULTS_TAGS_MISSING {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_TAGS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagtest for [{0}]: .
        /// </summary>
        internal static string TAGTEST_RESULTS_TEST_TYPE {
            get {
                return ResourceManager.GetString("TAGTEST_RESULTS_TEST_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule parsing failed for file {0}.
        /// </summary>
        internal static string VERIFY_RULE_LOADFILE_FAILED {
            get {
                return ResourceManager.GetString("VERIFY_RULE_LOADFILE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule {0} failed from dupicate rule id specified.
        /// </summary>
        internal static string VERIFY_RULES_DUPLICATEID_FAIL {
            get {
                return ResourceManager.GetString("VERIFY_RULES_DUPLICATEID_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule {0} failed from unrecognized language specified.
        /// </summary>
        internal static string VERIFY_RULES_LANGUAGE_FAIL {
            get {
                return ResourceManager.GetString("VERIFY_RULES_LANGUAGE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify default rules request from outside CLI call not supported.  Use custom rules option..
        /// </summary>
        internal static string VERIFY_RULES_NO_CLI_DEFAULT {
            get {
                return ResourceManager.GetString("VERIFY_RULES_NO_CLI_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule {0} failed from missing rule id.
        /// </summary>
        internal static string VERIFY_RULES_NULLID_FAIL {
            get {
                return ResourceManager.GetString("VERIFY_RULES_NULLID_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule {0} failed from invalid regex &apos;{1}&apos; with {2}.
        /// </summary>
        internal static string VERIFY_RULES_REGEX_FAIL {
            get {
                return ResourceManager.GetString("VERIFY_RULES_REGEX_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify rules failed.  See log file for details.
        /// </summary>
        internal static string VERIFY_RULES_RESULTS_FAIL {
            get {
                return ResourceManager.GetString("VERIFY_RULES_RESULTS_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify rules succeeded.
        /// </summary>
        internal static string VERIFY_RULES_RESULTS_SUCCESS {
            get {
                return ResourceManager.GetString("VERIFY_RULES_RESULTS_SUCCESS", resourceCulture);
            }
        }
    }
}
