parameters:
# Job Name
- name: jobName
  type: string
  default: 'dotnet_test'
# Version of Dotnet SDK to use
- name: dotnetVersion
  type: string
  default: '7.0.x'
# The framework to use for testing
- name: testFramework
  type: string
  default: 'net7.0'
# List of paths to .csproj
- name: projectPath
  type: string
  default: ''

jobs:
- job: ${{ parameters.jobName }}
  displayName: Dotnet Test
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    displayName: Install Dotnet SDK
    inputs:
      packageType: 'sdk'
      version: ${{ parameters.dotnetVersion }}
  - task: DotNetCoreCLI@2
    displayName: Dotnet Test
    inputs:
      command: 'test'
      projects: ${{ parameters.projectPath }}
      arguments: '-f ${{ parameters.TestFramework }} --collect "Code coverage"'
      publishTestResults: true
