parameters:
# Service Tree ID of application
- name: serviceTreeID
  type: string
  default: ''

jobs:
- job: sdl_tools
  displayName: SDL Tools
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: CodeInspector@2
    continueOnError: true
    inputs:
      ProductId: ${{ parameters.serviceTreeID }}
  - task: CredScan@3
    inputs:
      verboseOutput: true
  - task: PoliCheck@1
    inputs:
      inputType: 'Basic'
      targetType: 'F'
      targetArgument: '$(Build.SourcesDirectory)'
      result: 'PoliCheck.xml'
  - task: notice@0
    enabled: false
    continueOnError: true
    inputs:
      outputformat: 'text'
  - task: SdtReport@2
    inputs:
      GdnExportAllTools: true
  - task: PublishSecurityAnalysisLogs@2
    inputs:
        ArtifactName: 'CodeAnalysisLogs'
        ArtifactType: 'Container'
        AllTools: true
        ToolLogsNotFoundAction: 'Standard'